SlicerDMRI/SlicerDMRI

CMakeLists.txt
This commit will avoid the following warning:
//-----------------------------------------
Policy CMP0048 is not set: project() command manages VERSION variables.
Run "cmake --help-policy CMP0048" for policy details.  Use the cmake_policy
command to set the policy and suppress this warning.
The following variable(s) would be set to empty:
PROJECT_VERSION
PROJECT_VERSION_MAJOR
PROJECT_VERSION_MINOR
PROJECT_VERSION_PATCH
//-----------------------------------------
=> STYLE: Fix CMake 3.0 warning setting CMP0048 to NEW

Modules/CLI/FiberBundleLabelSelect/FiberBundleLabelSelect.xml
For consistency that the module names of other modules are
separated with Space.
Hi @ihnorton 
Just a minor update of the name displaced for the module. Thanks!
Regards,
Fan
=> STYLE: Update module name displayed with Space

Modules/CLI/DiffusionWeightedVolumeMasking/CMakeLists.txt, Modules/CLI/DiffusionWeightedVolumeMasking/DiffusionWeightedVolumeMasking.cxx, Modules/CLI/DiffusionWeightedVolumeMasking/DiffusionWeightedVolumeMasking.xml
Fixes https://github.com/SlicerDMRI/SlicerDMRI/issues/26 by selecting
baseline images using a threshold on the B-values rather than gradient
magnitude. Provides command line option to select threshold if needed
(default 100).
Prior to the change in [1], all images were potentially included in the mask
calculation because gradient components were rounded down
to zero [2]. After [1], some datasets are rejected because the 1e-6
tolerance criteria excludes low (non-zero) B-value volumes. For example,
in the issue #26 dataset, the baseline volumes have B-value 5.
[1] https://github.com/Slicer/Slicer/pull/380
[2] http://www.na-mic.org/Bug/view.php?id=3855
=> ENH: fix #26, improve #21 (baseline selection, and replace VTK filters)

Modules/CLI/FiberTractMeasurements/Testing/CompareTxts.cxx
1) Include "cstdlib" to fix this build error:
```
/home/jcfr/Projects/Slicer-Debug/DMRI/FiberTractMeasurements/Testing/CompareTxts.cxx: In function ‘int main(int, char**)’:
/home/jcfr/Projects/Slicer-Debug/DMRI/FiberTractMeasurements/Testing/CompareTxts.cxx:20:12: error: ‘EXIT_FAILURE’ was not declared in this scope
return EXIT_FAILURE;
^
```
2) Construct "ifstream" using char* signature  also available with c++ older
that c++11:
```
/home/jcfr/Projects/Slicer-Debug/DMRI/FiberTractMeasurements/Testing/CompareTxts.cxx:25:40: error: no matching function for call to ‘std::basic_ifstream<char>::basic_ifstream(std::__cxx11::string&)’
std::ifstream resultTxt(resultTxtPath);
^
```
=> COMP: CompareTxts: Fix build errors

Modules/CLI/DWIToDTIEstimation/Testing/CMakeLists.txt, Modules/CLI/DiffusionTensorScalarMeasurements/Testing/CMakeLists.txt
A little background for this pull request:
I am currently working on integrating the parameter serializer in Slicer. While integrating JsonCpp to the SlicerExecutionModel as a first step, I had link errors because of the missing libraries in the testing. This pulls request fixes that.
For more information, see https://www.slicer.org/slicerWiki/index.php/Documentation/Labs/ParameterSerializer
Thanks !
=> BUG: Make sure to link against CLI library in testing

Modules/Loadable/InteractiveSeeding/Logic/vtkSlicerTractographyInteractiveSeedingLogic.cxx, Modules/Loadable/InteractiveSeeding/qSlicerTractographyInteractiveSeedingModuleWidget.cxx, Modules/Loadable/InteractiveSeeding/qSlicerTractographyInteractiveSeedingModuleWidget.h
The feature allows setting nodes to their proper places in the GUI.
Subject hierarchy support also added so that output fiber tract is placed under the DTI volume in the hierarchy
=> ENH: Added edit node support to tractography interactive seeding

Libs/vtkDMRI/vtkSeedTracts.cxx, Modules/CLI/TractographyLabelMapSeeding/TractographyLabelMapSeeding.xml, Modules/Loadable/InteractiveSeeding/Logic/vtkMRMLTractographyInteractiveSeedingNode.cxx, Modules/Loadable/InteractiveSeeding/Logic/vtkMRMLTractographyInteractiveSeedingNode.h, Modules/Loadable/InteractiveSeeding/Logic/vtkSlicerTractographyInteractiveSeedingLogic.cxx, Modules/Loadable/InteractiveSeeding/qSlicerTractographyInteractiveSeedingModuleWidget.cxx, Modules/Loadable/InteractiveSeeding/qSlicerTractographyInteractiveSeedingModuleWidget.h
- 813704e fixes a UI bug, see the commit message for 415a5f1 for explanation.
- bb8d1a3, 978a147, and efa22a0 re-apply missing/reverted commits from #65 and #66.
=> BUG/ENH: use enums for UI<->SeedingNode settings

Modules/Loadable/TractographyDisplay/qSlicerTractographyDisplayModule.cxx
This commit updates the TractographyDisplay module to work with Slicer
following r26540 (BUG: Fix initialization of module displayable managers)
See http://viewvc.slicer.org/viewvc.cgi/Slicer4?view=revision&revision=26540
=> Ensure displayable manager are registered with Slicer >= 4.9

Modules/Loadable/TractographyDisplay/MRML/vtkMRMLFiberBundleTubeDisplayNode.cxx
Old bug (at least Slicer 4.5) I noticed fixing #87: 
- select orientation color modes
- return to color-by-tensor property
- model will be solid color only, until the selected invariant is changed.
Reason is:
This flag is reset when the pipeline is changed, so must be set again when re-enabling the
TensorToColor filter. Otherwise the model will appear solid until the selected invariant is
changed -- which triggers resetting this flag internally (but only on the expensive path if
selected invariant is actually changed).
=> BUG: fix color-by-tensorproperty after by-orientation

Modules/Loadable/TractographyDisplay/MRML/vtkMRMLFiberBundleDisplayNode.cxx, Modules/Loadable/TractographyDisplay/MRML/vtkMRMLFiberBundleNode.cxx, Modules/Loadable/TractographyDisplay/MRML/vtkMRMLFiberBundleNode.h, Modules/Loadable/TractographyDisplay/MRMLDM/vtkMRMLTractographyDisplayDisplayableManager.cxx, Modules/Loadable/TractographyDisplay/Widgets/Resources/UI/qSlicerTractographyEditorROIWidget.ui, Modules/Loadable/TractographyDisplay/Widgets/qSlicerTractographyDisplayWidget.cxx, Modules/Loadable/TractographyDisplay/Widgets/qSlicerTractographyEditorROIWidget.cxx
Fixes interactive sub-sampling and continuous ROI selection.
Fixes de-selecting ROI node.
Improves performance by hiding filter output behind passthrough.
Cleans up cruft.
=> WIP: refactor vtkMRMLFiberBundleNode (2/2)

Modules/Scripted/FiberBundleToLabelMap/FiberBundleToLabelMap.py
NumPy defaults to 'long' on Windows, which is int32. Use a helper inside VTK which has the correct dtype for vtkIdTypeArray.
=> BUG: fix crash in FB2LabelMap due to mismatched NumPy/VTK dtype size

Modules/Scripted/TractographyExportPLY/TractographyExportPLY.py
This fixes export of `colorModeSolid` nodes: previously the last-used scalar array would be attached, leading to unexpected colors in the exported data. Now we set a uniform color in the writer.
=> ENH: properly support PLY export of color-by-solid

Modules/Loadable/TractographyDisplay/MRML/vtkMRMLFiberBundleNode.cxx, Modules/Loadable/TractographyDisplay/MRMLDM/vtkMRMLTractographyDisplayDisplayableManager.cxx, Modules/Loadable/TractographyDisplay/Widgets/qSlicerTractographyDisplayModuleWidget.cxx, Modules/Loadable/TractographyDisplay/Widgets/qSlicerTractographyEditorROIWidget.cxx
Partially fixes the Interactive Edit feature. There is a remaining issue: activating the edit tool requires clicking in the render window after `Enable Interactive Edit` is checked. I think this is a state issue in the interactor node, but I'm not sure how to fix that yet.
also note that, as per a comment in the code, the 's' (select) feature currently only works with color-by-scalar mode.
=> BUG: fix Tractography Display 'Interactive Edit' feature

Modules/Scripted/DICOM2FullBrainTractography/DICOM2FullBrainTractographyLib/workflow_support.py
This aims to solve various [failing](http://slicer.cdash.org/testDetails.php?test=9642248&build=1608020) test cases for Slicer-Preview (aka nightly). 
The saferef module was removed from Slicer in https://github.com/Slicer/Slicer/commit/eb4570e90ed533228c4c68aa950e72a43258eb27.  
> Starting with Python 3.4, the weakref module available in python is improved to provide the 'weakref.WeakMethod' class.
=> BUG: Replace saferef with weakref

Modules/CLI/FiberBundleLabelSelect/CMakeLists.txt, Modules/CLI/TractographyLabelMapSeeding/CMakeLists.txt
TractographyLabelMapSeeding and FiberBundleLabelSelect do not
compile with VS2019 v142 toolset
=> COMP:  Disable Broken tests on Windows

Modules/CLI/FiberTractMeasurements/CMakeLists.txt
This should re-enable windows builds for the 4.10 release.
Based on this commit:
https://github.com/SlicerDMRI/SlicerDMRI/commit/ddb6c36d03f5c56a835440306e5dd84cebb0f576
=> Disable test that breaks windows build

Modules/Loadable/TractographyDisplay/Logic/vtkSlicerFiberBundleLogic.cxx
This function probably used to use raw pointers
and would have returned null if the file could
not be read, but the smart pointer is not null,
so it led to a crash.  Here we explicitly set
the smart pointer to nullptr so it will go away.
The crash would occur when trying to load a .trk
file which could not be loaded.
=> BUG: fix crash trying to load trk file

Modules/Loadable/TractographyDisplay/MRML/vtkMRMLFiberBundleNode.cxx, Modules/Loadable/TractographyDisplay/MRML/vtkMRMLFiberBundleNode.h, Modules/Loadable/TractographyDisplay/MRML/vtkMRMLFiberBundleStorageNode.cxx
During the 4.11 development process the convention
was introduced that all storage nodes would try to
be aware of the coordinate system conventions and
read/write them in files explicitly where possible.
See [1].
For data files that do not explicitly declare their
coordinate system, such as STL files for 3D printing,
it was decided that LPS was the most convention so so files
that don't declare a convention are treated as LPS.
The problem for SlicerDMRI is that the community has
many terabytes of .vtk and .vtp fiber bundle files that do
not declare that they are in RAS, so they the new convention
reads them as LPS.  These old files would not be
read properly even if newly written files were saved
with explicit coordinate system.
This fix allows existing fiber bundles to be loaded
and also …
=> BUG: explicitly flag all vtk fiber bundles RAS

Libs/vtkDMRI/CMakeLists.txt, Libs/vtkDMRI/vtkBSplineInterpolateImageFunction.h, Libs/vtkDMRI/vtkHyperStreamlineDTMRI.h, Libs/vtkDMRI/vtkHyperStreamlineTeem.h, Libs/vtkDMRI/vtkPolyDataColorLinesByOrientation.h, Libs/vtkDMRI/vtkPolyDataTensorToColor.h, Libs/vtkDMRI/vtkPreciseHyperStreamline.h, Libs/vtkDMRI/vtkPreciseHyperStreamlinePoints.h, Libs/vtkDMRI/vtkTeemEstimateDiffusionTensor.h, Libs/vtkDMRI/vtkTensorImplicitFunctionToFunctionSet.h, Libs/vtkDMRI/vtkTensorMask.h, Libs/vtkDMRI/vtkTensorRotate.h, Modules/CLI/FiberBundleLabelSelect/FiberBundleLabelSelect.cxx, Modules/Loadable/InteractiveSeeding/Logic/vtkMRMLTractographyInteractiveSeedingNode.h, Modules/Loadable/InteractiveSeeding/Logic/vtkSlicerTractographyInteractiveSeedingLogic.h, Modules/Loadable/TractIO/TractIOCLI/VTK_to_DICOMTract.cxx, Modules/Loadable/TractographyDisplay/Logic/vtkSlicerFiberBundleLogic.h, Modules/Loadable/TractographyDisplay/MRML/vtkMRMLFiberBundleDisplayNode.h, Modules/Loadable/TractographyDisplay/MRML/vtkMRMLFiberBundleGlyphDisplayNode.h, Modules/Loadable/TractographyDisplay/MRML/vtkMRMLFiberBundleLineDisplayNode.h, Modules/Loadable/TractographyDisplay/MRML/vtkMRMLFiberBundleNode.h, Modules/Loadable/TractographyDisplay/MRML/vtkMRMLFiberBundleStorageNode.h, Modules/Loadable/TractographyDisplay/MRML/vtkMRMLFiberBundleTubeDisplayNode.h, Modules/Loadable/TractographyDisplay/MRMLDM/vtkMRMLTractographyDisplayDisplayableManager.cxx, Modules/Loadable/TractographyDisplay/MRMLDM/vtkMRMLTractographyDisplayDisplayableManager.h, Modules/Loadable/TractographyDisplay/Testing/Cxx/vtkMRMLFiberBundleDisplayNodeTest1.cxx
* Replace `VTK_OVERRIDE` with override
* Update initialization of `vtkIdType*` ivar to comply
with updated `vtkPolyData` API.
* Fix `vtkDMRI` python wrapping excluding `PythonD` target with `VTK >= 8.90`
It fixes the following configuration error:
```
CMake Error at Libs/vtkDMRI/CMakeLists.txt:125 (set_target_properties):
set_target_properties Can not find target to add properties to:
vtkDMRIPythonD
CMake Error at Libs/vtkDMRI/CMakeLists.txt:131 (export):
export given target "vtkDMRIPythonD" which is not built by this project.
```
=> COMP: Add support for building against VTK 8.2.0 or 9.0.0

Modules/Loadable/TractographyDisplay/qSlicerFiberBundleReader.cxx
qSlicerFiberBundleReader::load wasn't checking parameters
carefully and could crash if fed bad input
=> BUG: avoid crash or assert on bad load arguments

Modules/Scripted/DMRIPlugins/DICOMDiffusionVolumePlugin.py
Previous code always assigned "Philips" as vendor if any tags for any vendor
matched. Also removed two tags which matched non-DWI Siemens volume.
Those tags were left as comments in case someone in the future wants to treat
those with more nuance and put them back in. Adjusted loadable tooltip to
list all matching vendors.
=> Fixed vendor name bug and removed erroneous tags

Modules/Loadable/TractographyDisplay/MRML/vtkMRMLFiberBundleNode.h
This exposes the vtk filter that selects fiber boundles. 
Thus, enables to programatically set custom functions.
See also #148
Thanks
=> use custom function to select fiber boundle

Modules/Loadable/TractographyDisplay/MRML/vtkMRMLFiberBundleNode.cxx
Fixes build error "no member named 'random_shuffle' in namespace 'std'"
(https://slicer.cdash.org/viewBuildError.php?buildid=2735613)
The error is due to `random_shuffle` was deprecated in C++14 and removed in C++17.
The replacement `shuffle` function takes a random generator as parameter.
More details: https://www.open-std.org/jtc1/sc22/wg21/docs/papers/2014/n4190.htm
=> COMP: Fix build error with C++17

Modules/Loadable/InteractiveSeeding/qSlicerTractographyInteractiveSeedingModule.cxx, Modules/Loadable/InteractiveSeeding/qSlicerTractographyInteractiveSeedingModule.h, Modules/Loadable/InteractiveSeeding/qSlicerTractographyInteractiveSeedingModuleWidget.h, Modules/Loadable/TractographyDisplay/Widgets/qMRMLTractographyDisplayTreeView.cxx, Modules/Loadable/TractographyDisplay/Widgets/qSlicerTractographyDisplayBasicWidget.h, Modules/Loadable/TractographyDisplay/Widgets/qSlicerTractographyDisplayGlyphWidget.h, Modules/Loadable/TractographyDisplay/Widgets/qSlicerTractographyDisplayModuleWidget.h, Modules/Loadable/TractographyDisplay/Widgets/qSlicerTractographyDisplayWidget.h, Modules/Loadable/TractographyDisplay/Widgets/qSlicerTractographyEditorROIWidget.h, Modules/Loadable/TractographyDisplay/qSlicerFiberBundleReader.cxx, Modules/Loadable/TractographyDisplay/qSlicerFiberBundleReader.h, Modules/Loadable/TractographyDisplay/qSlicerTractographyDisplayModule.cxx, Modules/Loadable/TractographyDisplay/qSlicerTractographyDisplayModule.h
Ensures the displayable manager is registered when the extension
is built against Slicer >=5. It removes the conditional check originally
introduced in 45eceb180 (Ensure displayable manager are registered with Slicer >= 4.9).
Runtime error fixed is the following:
```
Generic Warning: In /path/to/Slicer-Release/VTK/Common/Core/vtkDebugLeaks.cxx, line 272
Deleting unknown object: vtkMRMLTractographyDisplayDisplayableManager
Warning: In /path/to/Slicer/Libs/MRML/DisplayableManager/vtkMRMLDisplayableManagerFactory.cxx, line 136
vtkMRMLThreeDViewDisplayableManagerFactory (0x55b6315a8dd0): RegisterDisplayableManager - vtkMRMLTractographyDisplayDisplayableManager is not a displayable manager. Failed to register
```
=> Fix registration of Tractography displayable manager and remove support for Qt4 and Slicer 4

Modules/Loadable/InteractiveSeeding/CMakeLists.txt, Modules/Loadable/InteractiveSeeding/Logic/CMakeLists.txt, Modules/Loadable/InteractiveSeeding/Logic/vtkSlicerTractographyInteractiveSeedingLogic.cxx, Modules/Loadable/TractographyDisplay/MRML/vtkMRMLFiberBundleNode.cxx, Modules/Loadable/TractographyDisplay/MRML/vtkMRMLFiberBundleNode.h, Modules/Loadable/TractographyDisplay/MRMLDM/CMakeLists.txt, Modules/Loadable/TractographyDisplay/Widgets/CMakeLists.txt, Modules/Loadable/TractographyDisplay/Widgets/Resources/UI/qSlicerTractographyEditorROIWidget.ui, Modules/Loadable/TractographyDisplay/Widgets/qSlicerTractographyEditorROIWidget.cxx, Modules/Loadable/TractographyDisplay/Widgets/qSlicerTractographyEditorROIWidget.h
Since Annotations are deprected since Slicer 5, the corresponding MarkupsROI code is used. See linked issue for more details.
With this change the ROI node no longer has an `InteractiveMode`, which had been used to enable/disable hot-update of ROI selection and there does not appear to be a replacement in the Markups infrastructure.  However when using ROI selection it is actually the same to just disable ROI selection while editing the ROI and then switch back to positive or negative selection mode when ROI edit is finished.  Since this accomplishes the same result the checkbox is removed to simplify the code and the interface.
Fixes #158
=> ENH: Switch ROI selection from Annotations to Markups #158

Modules/Loadable/InteractiveSeeding/Logic/CMakeLists.txt, Modules/Loadable/TractographyDisplay/MRML/CMakeLists.txt
Follow on to https://github.com/SlicerDMRI/SlicerDMRI/commit/a2ca048a1896df5dcd43ecdffd191297a7ef25ac
Fixes #165
=> COMP: fix missing method link error

Modules/Loadable/TractographyDisplay/Testing/Python/SlicerMRBTest.py, Modules/Loadable/TractographyDisplay/Widgets/qMRMLSceneTractographyDisplayModel.cxx, Modules/Loadable/TractographyDisplay/Widgets/qMRMLTractographyDisplayTreeView.cxx, Modules/Loadable/TractographyDisplay/Widgets/qSlicerTractographyDisplayBasicWidget.cxx
Use `SetVisibility2D` instead of `SetSliceIntersectionVisibility` to toggle tractography tubes' 2D slice intersection visibility.
Fixes:
```
[VTK] Warning:
In /work/Stable/Slicer-0/Libs/MRML/Core/vtkMRMLDisplayNode.cxx, line 996
[VTK] vtkMRMLFiberBundleTubeDisplayNode (0x73bd250):
SetSliceIntersectionVisibility method is deprecated, please use SetVisibility2D instead
```
=> ENH: Use `SetVisibility2D` instead of `SetSliceIntersectionVisibility`

Modules/Loadable/TractographyDisplay/Logic/vtkSlicerFiberBundleLogic.cxx
The storage node was used but not saved in the scene, making the behavior inconsistent with corresponding method in the models superclass.
See discussion here: https://discourse.slicer.org/t/path-of-the-loaded-fiber-bundle/30524
=> BUG: add fiber storage node to the scene

Modules/Loadable/TractographyDisplay/Testing/Python/CMakeLists.txt
This commit removes workaround for issue Slicer/Slicer#4242 originally introduced in 2e5fb00d3 (COMP: work around python unittest runner bug for windows tests) and obsoleted following these Slicer commits:
* Slicer/Slicer@f07a6c3d7 (BUG: Teach 'slicer_add_python_unittest' to add module search paths)
* Slicer/Slicer@bd6a48784 (COMP: SlicerMacroPythonTesting: Fix typo in CMake variable)
=> COMP: Simplify TractographyDisplay Python tests removing obsolete workaround

README.md
Increase consistency in SlicerDMRI citation message:
- Prefer using https over http for web addresses when available.
- Use the website to refer to SlicerDMRI instead of the source code repository.
=> DOC: Increase consistency in SlicerDMRI citation message

License.txt
Sync the license file with the current Slicer license file content: https://github.com/Slicer/Slicer/blob/ce1ab3d3799ca9e11cc1175f4d0c8653d4837e11/License.txt
Specifically:
- Prefer using https over http for web addresses when available.
- Fix a typo following: https://github.com/Slicer/Slicer/commit/68ff0ae7114e4378322740f117643d7513a71110
- Add a blank line at the beginning of the file and remove an unnecessary whitespace in the text.
Make the file have the `.txt` extension instead of `.md` and make its name all lowercase to sync with the Slicer license file.
=> DOC: Sync the license file with the current Slicer license file content

Modules/CLI/FiberTractMeasurements/FiberTractMeasurements.cxx
Call explicitly `.c_str()` to get a `const char*`, instead of relying on the `operator const char *()` deprecated operator.
Fixes:
```
Modules/CLI/FiberTractMeasurements/FiberTractMeasurements.cxx:1024:27:
warning: 'operator const char *' is deprecated:
Call `.c_str()` explicitly [-Wdeprecated-declarations]
reader->SetFileName(fileNamesVTK->GetValue(i));
^
```
Raised for example in:
https://slicer.cdash.org/viewBuildError.php?type=1&buildid=3190094
=> COMP: Call explicitly `.c_str()` to get a `const char*`

Modules/Loadable/TractographyDisplay/MRML/vtkMRMLFiberBundleNode.cxx, Modules/Loadable/TractographyDisplay/MRML/vtkMRMLFiberBundleNode.h, Modules/Scripted/FiberBundleToLabelMap/FiberBundleToLabelMap.py
Prefer using `vtkExtractSelection` over the deprecated `vtkExtractSelectedPolyDataIds`.
Fixes:
```
Modules/Loadable/TractographyDisplay/MRML/vtkMRMLFiberBundleNode.cxx:107:49:
warning: 'vtkExtractSelectedPolyDataIds' is deprecated:
Use vtkExtractSelection instead of vtkExtractSelectedPolyDataIds.
[-Wdeprecated-declarations]
ExtractSubsample(vtkExtractSelectedPolyDataIds::New()),
^
```
Raised for example in:
https://slicer.cdash.org/viewBuildError.php?type=1&buildid=3190094
Documentation
https://vtk.org/doc/nightly/html/classvtkExtractSelectedPolyDataIds.html#details
=> COMP: Prefer using `vtkExtractSelection`

Libs/vtkDMRI/vtkTeemEstimateDiffusionTensor.cxx, Modules/Loadable/TractIO/TractIOCLI/VTK_to_DICOMTract.cxx
Prefer `snprintf` over `sprintf` to avoid buffer overruns.
Fixes:
```
Libs/vtkDMRI/vtkTeemEstimateDiffusionTensor.cxx:504:5:
warning: 'sprintf' is deprecated:
This function is provided for compatibility reasons only.
Due to security concerns inherent in the design of sprintf(3),
it is highly recommended that you use snprintf(3) instead.
[-Wdeprecated-declarations]
```
and similar warnings.
Raised for example in:
https://slicer.cdash.org/viewBuildError.php?type=1&buildid=3190094
=> COMP: Prefer `snprintf` to avoid buffer overruns

Libs/vtkDMRI/vtkTeemEstimateDiffusionTensor.cxx
Fix `sizeof` argument in `snprintf` call: dereference pointer to buffer.
Fixes:
```
Libs/vtkDMRI/vtkTeemEstimateDiffusionTensor.cxx:504:19:
warning: argument to ‘sizeof’ in ‘int snprintf(char*, size_t, const char*, ...)’
call is the same expression as the destination;
did you mean to provide an explicit length? [-Wsizeof-pointer-memaccess]
504 |     snprintf(err, sizeof(err), "%s:",this->GetClassName());
|                   ^~~~~~~~~~~
```
and similar warnings.
Raised for example at:
https://github.com/SlicerDMRI/SlicerDMRI/actions/runs/6679353771/job/18151381270#step:7:246
=> COMP: Fix `sizeof` argument in `snprintf` call

.github/workflows/build-test.yml
Test build: call `ctest` so that the tests are run.
Some tests launch Slicer's GUI: use the `coactions/setup-xvfb@v1.0.1` coaction so that `xvfb` is installed for when tests are run.
=> ENH: Test build

Modules/Loadable/TractographyDisplay/Testing/Data/Input/helix_roi_tract.mrml
Fix `vtkMRMLCameraNode::GetActiveTag()`  warning raised when running the `vtkMRMLFiberBundleNodeTest1`. Apply the following changes to the MRML scene file used by the test:
- Remove the obsolete `active` attribute from `Camera` element.
- Add `singletonTag="1"` before `attributes="MappedInLayout:1"` in the `View` element.
- Add `layoutName="1"` before `layoutLabel="1"` in  the `View` element.
Fixes:
```
vtkMRMLCameraNode.cxx:405   WARN| vtkMRMLCameraNode (0x55d39e09e730):
vtkMRMLCameraNode::GetActiveTag() is deprecated.
Use vtkMRMLCameraNode::GetLayoutName() instead.
```
Following
https://github.com/Slicer/Slicer/commit/e78f557cd0cc70587e6dc01fa4983447462b0db6
Fixes #212.
=> BUG: Fix input scene update in `vtkMRMLFiberBundleNodeTest1`

Modules/Scripted/DICOM2FullBrainTractography/DICOM2FullBrainTractographyLib/workflow_support.py
Fix weakref method warning: make the callback methods be methods of the `Workflow` class.
Fixes:
```
test_widgetRepresentation
(qSlicerDICOM2FullBrainTractographyModuleGenericTest.
qSlicerDICOM2FullBrainTractographyModuleGenericTest)
... Traceback (most recent call last):
File "SlicerDMRI-build/inner-build/lib/Slicer-5.4/qt-scripted-modules/DICOM2FullBrainTractography.py",
line 44, in setup
self.full_tractography_workflow = DICOM2FullBrainTractographyLib.Workflow(
File "SlicerDMRI-build/inner-build/lib/Slicer-5.4/qt-scripted-modules/DICOM2FullBrainTractographyLib/workflow_support.py",
line 82, in __init__
step = GeneralizedStep(step_widget_file, widget,
File "SlicerDMRI-build/inner-build/lib/Slicer-5.4/qt-scripted-modules/DICOM2FullBrainTractographyLib/workflow_support.py",
line 135, in …
```
=> BUG: Fix weakref method warning

Modules/Loadable/TractographyDisplay/Testing/Python/DTINotReproducibleIssue3977.py
Fix data download URLs and Slicer display message call in test:
- The Slicer testing data was moved from kitware midas hosting to GitHub repositories. Related thread: https://github.com/Slicer/Slicer/pull/4785
-  Use the `slicer.util` module to be able to call the `delayDisplay` method: the testing class `DTINotReproducibleIssue3977Logic` inherits from `ScriptedLoadableModuleLogic`, which does not have a parent class, and thus does not inherit the `delayDisplay` (as opposed to classes that inherit from `ScriptedLoadableModuleTest`.
Fixes:
```
File "SlicerDMRI/Modules/Loadable/TractographyDisplay/Testing/Python/DTINotReproducibleIssue3977.py",
line 147, in test_DTINotReproducibleIssue39771
volumeNode = slicer.util.getNode(pattern="dwi")
File …
```
=> BUG: Fix data download URLs and Slicer display message call

DMRIModuleTemplates/Tractography_Scripted/TemplateKey.py, Modules/CLI/ExtractDWIShells/ExtractDWIShells.py, Modules/Loadable/TractographyDisplay/Testing/Python/NsgPlanTracto.py, Modules/Loadable/TractographyDisplay/Testing/Python/SlicerMRBTest.py, Modules/Loadable/TractographyDisplay/Testing/Python/fiber_visibility_crash2438.py, Modules/Loadable/TractographyDisplay/Testing/Python/test_tractography_display.py, Modules/Scripted/DMRIPlugins/DICOMDiffusionVolumePlugin.py, Modules/Scripted/FiberBundleToLabelMap/FiberBundleToLabelMap.py, Modules/Scripted/TractographyDownsample/TractographyDownsample.py
Remove deprecated Python `import` statements: the statements:
```
from __future__ import print_function
from __future__ import division
```
are vestiges of code that was intended to support both Python 2 and Python 3. All Python 2 versions have reached their EOL since a few years now, so these `import`s are no longer required on any sensible Python version.
=> STYLE: Remove deprecated Python `import` statements

Modules/Loadable/TractographyDisplay/Widgets/qSlicerTractographyDisplayWidget.cxx, Modules/Loadable/TractographyDisplay/qSlicerFiberBundleReader.cxx
Use `toStdString().c_str()` instead of `toLatin1()` to get a `const char*`.
Documentation:
https://doc.qt.io/qt-5/qstring.html#toStdString
https://doc.qt.io/qt-5/qstring.html#toLatin1
=> STYLE: Use `toStdString().c_str()` instead of `toLatin1()` for `char*`

Modules/Loadable/TractIO/TractIOCLI/VTK_to_DICOMTract.cxx
Fix `CodeSequenceMacro` implict declaration warning: assign the instantiation arguments depending on the case and instantiate the class using them instead of using the assignment operator.
Fixes:
```
[215/263] Building CXX object Modules/Loadable/TractIO/TractIOCLI/CMakeFiles/VTK_to_DICOMTractLib.dir/VTK_to_DICOMTract.cxx.o
SlicerDMRI/Modules/Loadable/TractIO/TractIOCLI/VTK_to_DICOMTract.cxx:
In function ‘int insert_polydata_scalars(TrcTrackSet*, vtkSmartPointer<vtkPolyData>)’:
SlicerDMRI/SlicerDMRI/Modules/Loadable/TractIO/TractIOCLI/VTK_to_DICOMTract.cxx:401:60:
warning: implicitly-declared ‘CodeSequenceMacro& CodeSequenceMacro::operator=(const CodeSequenceMacro&)’ is deprecated [-Wdeprecated-copy]
401 |       unitCode = CodeSequenceMacro("mm2/s", "UCUM", "mm2/s");
| …
```
=> COMP: Fix `CodeSequenceMacro` implict declaration warning

Libs/vtkDMRI/vtkHyperPointandArray.h
Fix `vtkHyperPoint` implicit declaration warning: declare the copy constructor.
Fixes:
```
[50/263] Building CXX object Libs/vtkDMRI/CMakeFiles/vtkDMRIPython.dir/vtkHyperPointandArrayPython.cxx.o
SlicerDMRI/SlicerDMRI-build/inner-build/Libs/vtkDMRI/vtkHyperPointandArrayPython.cxx:
In function ‘PyObject* PyvtkHyperPoint_vtkHyperPoint_s2(PyObject*, PyObject*)’:
SlicerDMRI/SlicerDMRI-build/inner-build/Libs/vtkDMRI/vtkHyperPointandArrayPython.cxx:53:49:
warning: implicitly-declared ‘constexpr vtkHyperPoint::vtkHyperPoint(const vtkHyperPoint&)’ is deprecated [-Wdeprecated-copy]
53 |     vtkHyperPoint *op = new vtkHyperPoint(*temp0);
|                                                 ^
In file included from SlicerDMRI-build/inner-build/Libs/vtkDMRI/vtkHyperPointandArrayPython.cxx:10: …
```
=> COMP: Fix `vtkHyperPoint` implicit declaration warning

Libs/vtkDMRI/vtkTractographyPointAndArray.h
Fix `vtkTractographyPoint` implicit declaration warning: declare the copy constructor.
Fixes:
```
[57/263] Building CXX object Libs/vtkDMRI/CMakeFiles/vtkDMRIPython.dir/vtkTractographyPointAndArrayPython.cxx.o
SlicerDMRI/SlicerDMRI-build/inner-build/Libs/vtkDMRI/vtkTractographyPointAndArrayPython.cxx:
In function ‘PyObject* PyvtkTractographyPoint_vtkTractographyPoint_s2(PyObject*, PyObject*)’:
SlicerDMRI/SlicerDMRI-build/inner-build/Libs/vtkDMRI/vtkTractographyPointAndArrayPython.cxx:53:63:
warning: implicitly-declared ‘constexpr vtkTractographyPoint::vtkTractographyPoint(const vtkTractographyPoint&)’ is deprecated [-Wdeprecated-copy]
53 |     vtkTractographyPoint *op = new vtkTractographyPoint(*temp0);
|                                                               ^
In file included …
```
=> COMP: Fix `vtkTractographyPoint` implicit declaration warning

Modules/CLI/FiberTractMeasurements/FiberTractMeasurements.cxx
Fix the unused `topCluster` variable warning in `FiberTractMeasurements`: remove the variable.
The `topCluster` variable was originally introduced in 798a1e5 and its use became no longer necessary in 9bdd1d3, where it was left behind.
Fixes:
```
Modules/CLI/FiberTractMeasurements/FiberTractMeasurements.cxx:563:10:
warning: variable ‘topCluster’ set but not used [-Wunused-but-set-variable]
bool topCluster = true;
^~~~~~~~~~
```
reported on the 3D Slicer CDash server in the context of `preview` builds on CentOS 7 with GCC 7:
https://slicer.cdash.org/viewBuildError.php?type=1&buildid=3210886
=> COMP: Remove unused `topCluster` var from `FiberTractMeasurements`

README.md
Add a link to the Doxygen documentation GitHub Pages URL in the `README` file.
Take advantage of the commit to make the website, documentation and wiki links more visible using a list and bold font.
Add the GitHub Pages deployment status badge.
=> DOC: Add a link to the Doxygen documentation GitHub Pages URL in README

Modules/Loadable/TractographyDisplay/Testing/Python/NsgPlanTracto.py
Use `vtkMRMLMarkupsFiducialNode::SetNthControlPointPosition` instead of `vtkMRMLMarkupsFiducialNode::SetNthFiducialPosition`.
Fixes:
```
Warning: In vtkMRMLMarkupsFiducialNode.h, line 132
vtkMRMLMarkupsFiducialNode (0x557af863f8f0):
vtkMRMLMarkupsFiducialNode::SetNthFiducialPosition method is deprecated,
please use SetNthControlPointPosition instead
```
raised when running the `py_NsgPlanTracto` test.
The method was deprecated on Nov 28, 2021 through the Slicer commit: https://github.com/Slicer/Slicer/commit/73867d1c432842ee768ffb7693a4993070f5ff3c
=> COMP: Use SetNthControlPointPosition instead of SetNthFiducialPosition

Modules/CLI/ExtractDWIShells/ExtractDWIShells.py, Modules/Loadable/TractIO/DICOMTractographyPlugin.py, Modules/Loadable/TractographyDisplay/Testing/Python/DTINotReproducibleIssue3977.py, Modules/Loadable/TractographyDisplay/Testing/Python/NsgPlanTracto.py, Modules/Loadable/TractographyDisplay/Testing/Python/SlicerMRBTest.py, Modules/Loadable/TractographyDisplay/Testing/Python/fiber_visibility_crash2438.py, Modules/Loadable/TractographyDisplay/Testing/Python/test_tractography_display.py, Modules/Scripted/DICOM2FullBrainTractography/DICOM2FullBrainTractographyLib/workflow_support.py, Modules/Scripted/DMRIPlugins/DICOMDiffusionVolumePlugin.py, Modules/Scripted/FiberBundleToLabelMap/FiberBundleToLabelMap.py, Modules/Scripted/TractographyDownsample/TractographyDownsample.py, Modules/Scripted/TractographyExportPLY/TractographyExportPLY.py
=> STYLE: Prefer using f-strings

Modules/CLI/FiberTractMeasurements/FiberTractMeasurements.cxx
Remove unnecessary whitespaces around separator in fiber measurement stat printing and serialization. These whitespaces make it such that:
- The column names have some unnecessary/unexpected/undesired head and tail whitespaces, which makes it such that to call a column programmatically we need to do e.g. `[" Num_Fibers "]` instead of the expected `["Num_Fibers"]`.
- Numerical data are considered as strings or objects, and not as scalars.
So removing such whitespaces at the time of writing the data to a CSV file becomes necessary to ease automation/object manipulation downstream.
=> ENH: Remove unnecessary stat serialization whitespaces around separator

Modules/Scripted/DMRIPlugins/DICOMDiffusionVolumePlugin.py, Modules/Scripted/TractographyExportPLY/TractographyExportPLY.py
Fix syntax errors raised after introducing f-strings.
Fixes:
```
SlicerDMRI-build/inner-build/lib/Slicer-5.7/qt-scripted-modules/DICOMDiffusionVolumePlugin.py, line 115
loadable.tooltip = f"Matches DICOM tags for the following vendor(s): {', '.join(matchingVendors)}")
^
SyntaxError: unmatched ')'
```
and
```
SlicerDMRI-build/inner-build/lib/Slicer-5.7/qt-scripted-modules/TractographyExportPLY.py, line 306
self.delayDisplay(f"Test caused exception!\n"{str(e)}")
^
SyntaxError: invalid syntax
```
raised for example at:
https://github.com/SlicerDMRI/SlicerDMRI/actions/runs/7130356243/job/19416548387#step:8:541 https://github.com/SlicerDMRI/SlicerDMRI/actions/runs/7130356243/job/19416548387#step:8:559
Introduced inadvertently in commit 56b282f.
=> BUG: Fix syntax errors raised after introducing f-strings

Modules/Scripted/DICOM2FullBrainTractography/DICOM2FullBrainTractographyLib/workflow_support.py
Fix syntax errors raised after introducing f-strings.
Fixes:
```
Compiling qt-scripted-modules/DICOM2FullBrainTractographyLib/workflow_support.py ...
File "qt-scripted-modules/DICOM2FullBrainTractographyLib/workflow_support.py", line 240
this_module.__all__.append(function_name)
^
SyntaxError: invalid syntax
```
raised for example at:
https://github.com/SlicerDMRI/SlicerDMRI/actions/runs/7132804489/job/19424129633?pr=224#step:7:272
Introduced inadvertently in commit 56b282f and left behind in ee1f772.
=> BUG: Fix syntax errors raised after introducing f-strings (follow-up)

DMRIModuleTemplates/DWI_Scripted/TemplateKey.py, DMRIModuleTemplates/Tractography_Scripted/TemplateKey.py, Modules/Loadable/TractographyDisplay/Testing/Python/SlicerMRBTest.py, Modules/Loadable/TractographyDisplay/Testing/Python/fiber_visibility_crash2438.py, Modules/Loadable/TractographyDisplay/Testing/Python/test_tractography_display.py, Modules/Scripted/FiberBundleToLabelMap/FiberBundleToLabelMap.py
Fix data download URLs in tests: the Slicer testing data was moved from kitware midas hosting to GitHub repositories. Related thread: https://github.com/Slicer/Slicer/pull/4785
Fixes:
```
12: ERROR: test_fiber_visibility_crash24381 (fiber_visibility_crash2438.fiber_visibility_crash2438Test)
12: Ideally you should have several levels of tests.  At the lowest level
12: ----------------------------------------------------------------------
12: Traceback (most recent call last):
12:   File "SlicerDMRI/Modules/Loadable/TractographyDisplay/Testing/Python/fiber_visibility_crash2438.py",
line 203, in test_fiber_visibility_crash24381
12:     tractNode = slicer.util.getNode('tract1')
12:   File "Slicer-build/bin/Python/slicer/util.py", line 1566, in getNode
12:     raise …
```
=> BUG: Fix data download URLs in tests

Modules/Loadable/TractographyDisplay/Widgets/qSlicerTractographyDisplayWidget.cxx
Since a vtkMRMLModelNode can be either a vtkPolyData or a vtkUnstructuredGrid, use the generic GetMesh method to set the value for the scalar selection combobox.
Fixes #227
=> BUG: handle scalar colors when fibers are unstructured grid

CMakeLists.txt, Modules/Scripted/NIfTIFile/CMakeLists.txt, Modules/Scripted/NIfTIFile/NIfTIFile.py
This creates a reader plugin for Slicer that recognizes nii.gz files and offers to read them as diffusion volumes.
Relies on this work:
Billah, Tashrif; Bouix; Sylvain; Rathi, Yogesh; Various MRI Conversion Tools, https://github.com/pnlbwh/conversion, 2019, DOI: 10.5281/zenodo.2584003
Supported by NIH Grant 5R01MH119222
=> ENH: add nifti file reader for diffusion scans

Modules/Scripted/NIfTIFile/NIfTIFile.py
Use the github release link to pip install the python dependency needed for loading nifti files
=> ENH: Do not require git to install conversion package
